module.exports={
    EMPLOYEE_COLLECTION:'employees',
    USER_COLLECTIONS:'users',
    PRODUCT_COLLECTION:'products',
    PRODUCT_COLLECTION_BY_STORE:'stores_products',
    CART_COLLECTIONS:'carts',
    ORDER_COLLECTION:'orders',
    STORE_COLLECTION:'stores',
    USER_ADDRESS_COLLECTION:'user_address'
}